[2021-07-11 16:46:16] INFO (NNIDataStore) Datastore initialization done
[2021-07-11 16:46:16] INFO (RestServer) RestServer start
[2021-07-11 16:46:16] INFO (RestServer) RestServer base port is 8081
[2021-07-11 16:46:16] INFO (main) Rest server listening on: http://0.0.0.0:8081
[2021-07-11 16:46:20] INFO (NNIManager) Starting experiment: co8vtgzk
[2021-07-11 16:46:20] INFO (NNIManager) Setup training service...
[2021-07-11 16:46:20] INFO (LocalTrainingService) Construct local machine training service.
[2021-07-11 16:46:20] INFO (NNIManager) Setup tuner...
[2021-07-11 16:46:20] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-07-11 16:46:20] INFO (NNIManager) Add event listeners
[2021-07-11 16:46:20] INFO (LocalTrainingService) Run local machine training service.
[2021-07-11 16:46:25] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-07-11 18:09:46] ERROR (NNIManager) Dispatcher error: This socket has been ended by the other party
[2021-07-11 18:09:46] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:584:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.incomingStream.on (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\ipcInterface.js:41:72)
    at Socket.emit (events.js:203:15)
    at Socket.writeAfterFIN [as write] (net.js:399:8)
    at IpcInterface.sendCommand (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\ipcInterface.js:49:38)
    at NNIManager.pingDispatcher (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:428:29)
[2021-07-11 18:09:46] ERROR (NNIExperimentsManager) { Error: ENOENT: no such file or directory, open 'C:\Users\Chen Tzu-An\nni-experiments\.experiment.lock.1072'
    at Object.openSync (fs.js:443:3)
    at Object.exports.lockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\node_modules\lockfile\lockfile.js:277:17)
    at Object.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\common\utils.js:367:14)
    at NNIExperimentsManager.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:91:24)
    at NNIExperimentsManager.setExperimentInfo (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:55:18)
    at NNIManager.setEndtime (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:705:32)
    at NNIManager.logError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:693:14)
    at NNIManager.criticalError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:685:14)
    at EventEmitter.dispatcher.onError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:584:18)
    at EventEmitter.emit (events.js:198:13)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'C:\\Users\\Chen Tzu-An\\nni-experiments\\.experiment.lock.1072' }
[2021-07-11 18:09:46] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2021-07-11 18:09:46] ERROR (NNIExperimentsManager) { Error: ENOENT: no such file or directory, open 'C:\Users\Chen Tzu-An\nni-experiments\.experiment.lock.1072'
    at Object.openSync (fs.js:443:3)
    at Object.exports.lockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\node_modules\lockfile\lockfile.js:277:17)
    at Object.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\common\utils.js:367:14)
    at NNIExperimentsManager.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:91:24)
    at NNIExperimentsManager.setExperimentInfo (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:55:18)
    at NNIManager.setStatus (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:700:36)
    at NNIManager.logError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:694:14)
    at NNIManager.criticalError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:685:14)
    at EventEmitter.dispatcher.onError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:584:18)
    at EventEmitter.emit (events.js:198:13)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'C:\\Users\\Chen Tzu-An\\nni-experiments\\.experiment.lock.1072' }
[2021-07-11 18:09:46] ERROR (NNIManager) Dispatcher error: This socket has been ended by the other party
[2021-07-11 18:09:46] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:584:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\ipcInterface.js:42:72)
    at Socket.emit (events.js:203:15)
    at Socket.writeAfterFIN [as write] (net.js:399:8)
    at IpcInterface.sendCommand (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\ipcInterface.js:49:38)
    at NNIManager.pingDispatcher (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:428:29)
[2021-07-11 18:09:46] ERROR (NNIExperimentsManager) { Error: ENOENT: no such file or directory, open 'C:\Users\Chen Tzu-An\nni-experiments\.experiment.lock.1072'
    at Object.openSync (fs.js:443:3)
    at Object.exports.lockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\node_modules\lockfile\lockfile.js:277:17)
    at Object.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\common\utils.js:367:14)
    at NNIExperimentsManager.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:91:24)
    at NNIExperimentsManager.setExperimentInfo (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:55:18)
    at NNIManager.setEndtime (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:705:32)
    at NNIManager.logError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:693:14)
    at NNIManager.criticalError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:685:14)
    at EventEmitter.dispatcher.onError (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nnimanager.js:584:18)
    at EventEmitter.emit (events.js:198:13)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'C:\\Users\\Chen Tzu-An\\nni-experiments\\.experiment.lock.1072' }
[2021-07-11 18:09:46] WARNING (IpcInterface) Commands jammed in buffer!
[2021-07-11 18:12:44] ERROR (NNIRestHandler) { Error: ENOENT: no such file or directory, open 'C:\Users\Chen Tzu-An\nni-experiments\.experiment'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at NNIExperimentsManager.readExperimentsInfo (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:94:27)
    at Object.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\common\utils.js:368:20)
    at NNIExperimentsManager.withLockSync (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:91:24)
    at NNIExperimentsManager.withLockIterated (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:80:25)
    at NNIExperimentsManager.getExperimentsInfo (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\core\nniExperimentsManager.js:17:37)
    at router.get (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\rest_server\restHandler.js:276:37)
    at Layer.handle [as handle_request] (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Chen Tzu-An\Anaconda3\envs\python3.6\lib\site-packages\nni_node\node_modules\express\lib\router\route.js:137:13)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Chen Tzu-An\\nni-experiments\\.experiment' }
